(DATA  a)
(FUNCTION  addThem  []
  (BB 2
    (OPER 3 Func_Entry []  [])
  )
  (BB 3
    (OPER 4 Add_I [(r 4)]  [(r 1)(r 2)])
    (OPER 5 Mov [(r 3)]  [(r 4)])
    (OPER 6 Mov [(m RetReg)]  [(r 3)])
    (OPER 7 Jmp []  [(bb 1)])
  )
  (BB 1
    (OPER 1 Func_Exit []  [])
    (OPER 2 Return []  [(m RetReg)])
  )
)
(FUNCTION  main  []
  (BB 2
    (OPER 3 Func_Entry []  [])
  )
  (BB 3
    (OPER 4 Mov [(r 1)]  [(r 6)])
    (OPER 5 EQ [(r 8)]  [(r 1)(r 7)])
    (OPER 6 BEQ []  [(r 8)(i 0)(bb 6)])
  )
  (BB 4
    (OPER 7 Store []  [(r 9)(s a)])
  )
  (BB 5
    (OPER 10 Mov [(r 3)]  [(r 11)])
    (OPER 11 Mov [(r 5)]  [(r 12)])
    (OPER 12 LTE [(r 14)]  [(r 5)(r 13)])
    (OPER 13 BEQ []  [(r 14)(i 0)(bb 8)])
  )
  (BB 7
    (OPER 14 Add_I [(r 15)]  [(r 3)(r 5)])
    (OPER 15 Mov [(r 3)]  [(r 15)])
    (OPER 16 Add_I [(r 17)]  [(r 5)(r 16)])
    (OPER 17 Mov [(r 5)]  [(r 17)])
    (OPER 18 LTE [(r 19)]  [(r 5)(r 18)])
    (OPER 19 BNE []  [(r 19)(i 0)(bb 7)])
  )
  (BB 8
    (OPER 20 Div_I [(r 21)]  [(r 3)(r 20)])
    (OPER 21 Mov [(r 4)]  [(r 21)])
    (OPER 22 Mul_I [(r 23)]  [(r 4)(r 22)])
    (OPER 23 Mov [(r 3)]  [(r 23)])
    (OPER 24 Load [(r 24)]  [(s a)])
    (OPER 25 Pass []  [(r 24)] [(PARAM_NUM 0)])
    (OPER 26 Pass []  [(r 1)] [(PARAM_NUM 1)])
    (OPER 27 JSR []  [(s addThem)] [(numParams 2)])
    (OPER 28 Mov [(r 25)]  [(m RetReg)])
    (OPER 29 Mov [(r 2)]  [(r 25)])
    (OPER 30 Add_I [(r 26)]  [(r 2)(r 3)])
    (OPER 31 Pass []  [(r 26)] [(PARAM_NUM 0)])
    (OPER 32 JSR []  [(s putchar)] [(numParams 1)])
    (OPER 33 Mov [(r 27)]  [(m RetReg)])
    (OPER 34 Pass []  [(r 28)] [(PARAM_NUM 0)])
    (OPER 35 JSR []  [(s putchar)] [(numParams 1)])
    (OPER 36 Mov [(r 29)]  [(m RetReg)])
    (OPER 37 Mov [(m RetReg)]  [(r 30)])
    (OPER 38 Jmp []  [(bb 1)])
  )
  (BB 1
    (OPER 1 Func_Exit []  [])
    (OPER 2 Return []  [(m RetReg)])
  )
  (BB 6
    (OPER 8 Store []  [(r 10)(s a)])
    (OPER 9 Jmp []  [(bb 5)])
  )
)
